{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gzac-backend.fullname" . }}
  labels:
    {{- include "gzac-backend.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.settings.spring.datasource.password | toString | b64enc | quote }}
  SPRINGACTUATOR_PASSWORD: {{ .Values.settings.spring.actuator.password | toString | b64enc | quote }}
  KEYCLOAK_CREDENTIALS_SECRET: {{ .Values.settings.keycloak.clientSecret | toString | b64enc | quote }}
  VALTIMO_CONNECTORENCRYPTION_SECRET: {{ .Values.settings.gzac.connectorEncryptionSecret | toString | b64enc | quote }}
  CAMUNDA_BPM_ADMINUSER_PASSWORD: {{ .Values.settings.camunda.adminUserPassword | toString | b64enc | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAKAPI_CLIENTSECRET: {{ .Values.settings.spring.security.oauth2.client.registration.keycloakapi.clientSecret | toString | b64enc | quote }}
{{- end }}
